# Generated by Django 3.2.4 on 2021-06-30 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nome')),
                ('descricao', models.CharField(blank=True, max_length=150, null=True, verbose_name='Descricao')),
                ('dataCriacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('dataAtualizacao', models.DateTimeField(auto_now=True, verbose_name='Última data de atualização')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nome')),
                ('sexo', models.CharField(choices=[('F', 'Feminino'), ('M', 'Masculino'), ('N', 'Nenhuma das opções')], max_length=1)),
                ('cidade', models.CharField(blank=True, max_length=150, null=True, verbose_name='Cidade')),
                ('estado', models.CharField(blank=True, max_length=150, null=True, verbose_name='Estado')),
                ('pais', models.CharField(blank=True, max_length=150, null=True, verbose_name='País')),
                ('dataCriacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('dataAtualizacao', models.DateTimeField(auto_now=True, verbose_name='Última data de atualização')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nome')),
                ('sexo', models.CharField(choices=[('F', 'Feminino'), ('M', 'Masculino'), ('N', 'Nenhuma das opções')], max_length=1)),
                ('dataCriacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('dataAtualizacao', models.DateTimeField(auto_now=True, verbose_name='Última data de atualização')),
            ],
            options={
                'verbose_name': 'Vendedor',
                'verbose_name_plural': 'Vendedores',
            },
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formaPagamento', models.CharField(choices=[('C', 'Cartão crédito'), ('D', 'Cartão débito'), ('V', 'A vista'), ('P', 'PIX'), ('T', 'Transferência'), ('B', 'Boleto')], max_length=1, verbose_name='Forma de pagamento')),
                ('formaDivulgacao', models.CharField(choices=[('R', 'Redes sociais'), ('T', 'TV'), ('I', 'Indicação de amigos'), ('Y', 'YouTube')], max_length=1, verbose_name='Forma de divulgação')),
                ('dataCriacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('dataAtualizacao', models.DateTimeField(auto_now=True, verbose_name='Última data de atualização')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cliente', verbose_name='Cliente')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.vendedor', verbose_name='Vendedor')),
            ],
            options={
                'verbose_name': 'Carrinho',
                'verbose_name_plural': 'Carrinhos',
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nome')),
                ('descricao', models.CharField(blank=True, max_length=250, null=True, verbose_name='Descricao')),
                ('precoCusto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preço de custo')),
                ('precoVenda', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preço de custo')),
                ('dataCriacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('dataAtualizacao', models.DateTimeField(auto_now=True, verbose_name='Última data de atualização')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.categoria', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
        migrations.CreateModel(
            name='ItensVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(blank=True, null=True, verbose_name='Quantidade')),
                ('dataCriacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('dataAtualizacao', models.DateTimeField(auto_now=True, verbose_name='Última data de atualização')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.produto', verbose_name='Produto')),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.venda', verbose_name='Venda')),
            ],
            options={
                'verbose_name': 'Itens da Venda',
                'verbose_name_plural': 'Itens da Venda',
            },
        ),
    ]
