# Generated by Django 3.2.4 on 2021-06-30 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name': 'Categoria', 'verbose_name_plural': '1 - Categorias'},
        ),
        migrations.AlterModelOptions(
            name='cliente',
            options={'verbose_name': 'Cliente', 'verbose_name_plural': '4 - Clientes'},
        ),
        migrations.AlterModelOptions(
            name='itensvenda',
            options={'verbose_name': 'Itens da Venda', 'verbose_name_plural': '6 - Itens da Venda'},
        ),
        migrations.AlterModelOptions(
            name='produto',
            options={'verbose_name': 'Produto', 'verbose_name_plural': '2 - Produtos'},
        ),
        migrations.AlterModelOptions(
            name='venda',
            options={'verbose_name': 'Venda', 'verbose_name_plural': '5 - Venda'},
        ),
        migrations.AlterModelOptions(
            name='vendedor',
            options={'verbose_name': 'Vendedor', 'verbose_name_plural': '3 - Vendedores'},
        ),
        migrations.AddField(
            model_name='venda',
            name='statusPedido',
            field=models.CharField(choices=[('1', 'Carrinho'), ('2', 'Fechado'), ('3', 'Pago'), ('4', 'Saiu para a entrega'), ('5', 'Entregue')], default=1, max_length=1, verbose_name='Status do pedido'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='produto',
            name='precoVenda',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preço de venda'),
        ),
    ]
